replicaCount: 2

image:
  repository: adirremi/apiclusterapp-fastapi
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

postgres:
  externalHost: 34.71.236.251
  username: user
  passwordSecretName: db-secret # שם הסיקרט שבו הסיסמה מאוחסנת
  passwordSecretKey: DB_PASSWORD # המפתח בתוך הסיקרט שמחזיק את הסיסמה
  dbname: mydb
  port: 5432

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: "tf-fastapi"


ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
