apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: adirremi/apiclusterapp-fastapi:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@34.71.236.251:5432/mydb
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
