version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://user:password@34.71.236.251:5432/mydb
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
