apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-fallen-soldiers
  labels:
    app: {{ include "fastpostapp.name" . }}
spec:
  schedule: "1 0 * * *"  # מריץ את הקוד כל יום בשעה 00:01
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-fallen-soldiers
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecretName }}
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecretName }}
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecretName }}
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecretName }}
                  key: {{ .Values.postgres.passwordSecretKey }}
          restartPolicy: OnFailure
